import { randomUUID } from 'node:crypto'
import { evaluateAction } from './policy.js'
import { approvalIntentHash, evidenceHeadFor } from './approval-intent.js'
import type { RuntimeAdapter, RuntimeContext } from './runtime-adapter.js'
import { writeModeArtifacts } from './mode-artifacts.js'
import { validateModeArtifacts } from './artifact-validation.js'

const pause = (milliseconds: number, signal: AbortSignal) => new Promise<void>((resolve, reject) => {
  if (signal.aborted) return reject(new DOMException('Task cancelled', 'AbortError'))
  const abort = () => { clearTimeout(timer); reject(new DOMException('Task cancelled', 'AbortError')) }
  const timer = setTimeout(() => { signal.removeEventListener('abort', abort); resolve() }, milliseconds)
  signal.addEventListener('abort', abort, { once: true })
})

const previewHtml = (title: string) => `<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>${title.replaceAll('<', '&lt;')}</title>
  <style>
    :root { color-scheme: dark; font-family: Inter, ui-sans-serif, system-ui; background:#090b0a; color:#f4f7f5; }
    * { box-sizing:border-box } body { margin:0; min-height:100vh; display:grid; place-items:center; overflow:hidden; }
    body:before { content:""; position:fixed; inset:-20%; background:radial-gradient(circle at 65% 30%,rgba(42,210,120,.18),transparent 28%),linear-gradient(rgba(255,255,255,.025) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,.025) 1px,transparent 1px); background-size:auto,48px 48px,48px 48px; transform:perspective(700px) rotateX(58deg) translateY(18%); }
    main { width:min(860px,90vw); position:relative; padding:64px; border:1px solid #27302b; background:rgba(14,17,15,.86); box-shadow:0 32px 100px #000; }
    .eyebrow { color:#35dc7c; font:600 12px ui-monospace; letter-spacing:.16em; text-transform:uppercase; }
    h1 { font-size:clamp(42px,7vw,86px); line-height:.92; letter-spacing:-.06em; max-width:760px; margin:20px 0 28px; }
    p { color:#a7b0aa; font-size:18px; line-height:1.6; max-width:650px; }
    .status { display:flex; gap:9px; align-items:center; margin-top:36px; color:#dce5df; font-size:13px; }
    .dot { width:8px; height:8px; border-radius:50%; background:#35dc7c; box-shadow:0 0 20px #35dc7c; }
  </style>
</head>
<body><main><div class="eyebrow">ONEVibe generated artifact</div><h1>${title.replaceAll('<', '&lt;')}</h1><p>Built inside a path-confined local workspace. Publication remains withheld until a separate VTI Wallet provides an intent-bound approval.</p><div class="status"><span class="dot"></span> Source ready · policy evaluated · preview isolated</div></main></body>
</html>`

export class DemoRuntimeAdapter implements RuntimeAdapter {
  readonly name = 'demo'

  async run({ task, store, signal, prompt, requestUserInput }: RuntimeContext) {
    signal.throwIfAborted()
    await store.updateTask(task.id, { status: 'running' })
    await store.appendEvent(task.id, {
      type: 'run_started', lane: 'control', status: 'running', label: 'Task started',
      content: 'Local demo runtime started. This proves UX and event contracts, not VM isolation.',
      payload: { executionRoute: 'local_demo', securityBoundary: 'path_confined_process' },
    })
    await store.setPlanStep(task.id, 'scope', 'running')
    await pause(320, signal)
    await store.appendEvent(task.id, {
      type: 'assistant_text_delta', lane: 'transcript',
      content: 'I’ll turn this into a working artifact, keep the runtime boundary visible, and withhold public release until an external wallet approves it.',
      payload: {},
    })
    if (/\b(?:ask me|confirm with me|need my input)\b/i.test(prompt)) {
      const answer = await requestUserInput('Which deployment region should this workspace use?', ['Singapore', 'Virginia', 'Local only'], signal)
      await store.appendEvent(task.id, {
        type: 'assistant_text_delta', lane: 'transcript',
        content: `Thanks — I’ll continue with “${answer}” as the selected region.`, payload: { inputApplied: true },
      })
    }
    await store.setPlanStep(task.id, 'scope', 'completed')

    await store.setPlanStep(task.id, 'workspace', 'running')
    await pause(300, signal)
    const workspaceDecision = evaluateAction('write_workspace')
    await store.appendEvent(task.id, {
      type: 'activity_delta', lane: 'activity', label: 'Workspace policy evaluated',
      content: workspaceDecision.reason, payload: workspaceDecision,
    })
    await store.writeWorkspaceFile(task.id, 'README.md', `# ${task.title}\n\nGenerated by the ONEVibe local demo runtime.\n`)
    await store.setPlanStep(task.id, 'workspace', 'completed')

    await store.setPlanStep(task.id, 'build', 'running')
    const writeToolUseId = `demo_write_${randomUUID().replaceAll('-', '').slice(0, 12)}`
    await store.appendEvent(task.id, {
      type: 'tool_call_started', lane: 'activity', label: 'Write source files',
      content: 'Creating the preview and project metadata.', payload: {
        executionRoute: 'local_demo', toolUseId: writeToolUseId, toolName: 'workspace.write',
        input: { operation: 'write', paths: ['README.md', 'index.html', 'manifest.json'], mode: task.mode },
      },
    })
    await pause(500, signal)
    await store.writeWorkspaceFile(task.id, 'index.html', previewHtml(task.title))
    await store.writeWorkspaceFile(task.id, 'manifest.json', `${JSON.stringify({ name: task.title, generatedBy: 'onevibe-demo', sourcePrompt: task.prompt, latestInstruction: prompt, public: false }, null, 2)}\n`)
    const modeFiles = await writeModeArtifacts(task, store)
    await store.appendEvent(task.id, {
      type: 'tool_call_completed', lane: 'activity', label: 'Source files written',
      content: `${modeFiles.length + 3} files are available in the task workspace.`, payload: {
        executionRoute: 'local_demo', toolUseId: writeToolUseId, toolName: 'workspace.write',
        result: 'success', mode: task.mode, modeFiles,
      },
    })
    for (const filePath of modeFiles.filter((path) => path !== 'index.html')) {
      const isSlideDeck = filePath === 'deck.pptx' || filePath === 'deck.pdf'
      await store.appendEvent(task.id, {
        type: 'artifact_created', lane: 'artifact', label: isSlideDeck ? 'Slide deck export' : 'Mode artifact', content: filePath,
        payload: { executionRoute: 'local_demo', kind: isSlideDeck ? 'slide_deck' : 'mode_artifact', mode: task.mode },
      })
    }
    await store.appendEvent(task.id, {
      type: 'artifact_created', lane: 'artifact', label: 'Interactive preview',
      content: 'index.html', payload: { kind: 'website', uri: `/api/tasks/${task.id}/preview`, version: 1 },
    })
    await store.updateTask(task.id, { previewPath: `/api/tasks/${task.id}/preview` })
    await store.setPlanStep(task.id, 'build', 'completed')

    await store.setPlanStep(task.id, 'verify', 'running')
    await pause(380, signal)
    const validateToolUseId = `demo_validate_${randomUUID().replaceAll('-', '').slice(0, 12)}`
    await store.appendEvent(task.id, {
      type: 'tool_call_started', lane: 'activity', label: 'Validate artifact contract',
      content: 'Checking required outputs, portable metadata, preview semantics, and obvious credential leaks.', payload: {
        executionRoute: 'local_demo', toolUseId: validateToolUseId, toolName: 'artifact.validate',
        input: { mode: task.mode, checks: ['required outputs', 'metadata', 'preview semantics', 'credential-like values'] },
      },
    })
    const validation = await validateModeArtifacts(task, store)
    await store.appendEvent(task.id, {
      type: 'tool_call_completed', lane: 'activity', label: validation.passed ? 'Artifact contract passed' : 'Artifact contract needs review',
      content: validation.passed ? `${validation.checks.length} static checks passed. Runtime and browser validation remain separate gates.` : 'One or more static checks failed; inspect validation-report.json before handoff.',
      payload: {
        executionRoute: 'local_demo', toolUseId: validateToolUseId, toolName: 'artifact.validate',
        passed: validation.passed, report: 'validation-report.json', checkCount: validation.checks.length,
      },
    })
    const publishDecision = evaluateAction('publish_preview')
    const approvalId = `approval_${randomUUID().replaceAll('-', '').slice(0, 12)}`
    const expiresAt = new Date(Date.now() + 15 * 60_000).toISOString()
    const walletUrl = `openvtc://trust-task/${approvalId}`
    const evidenceHash = evidenceHeadFor(store.listEvents(task.id))
    const intentHash = approvalIntentHash({ approvalId, taskId: task.id, action: 'publish_preview', expiresAt, evidenceHash })
    await store.updateTask(task.id, {
      approval: { id: approvalId, action: 'publish_preview', intentHash, evidenceHash, state: 'pending', walletUrl, expiresAt },
    })
    await store.appendEvent(task.id, {
      type: 'approval_requested', lane: 'approval', status: 'waiting_for_approval',
      label: 'External approval required', content: publishDecision.reason,
      payload: { approvalId, action: 'publish_preview', intentHash, evidenceHash, walletUrl, expiresAt, policy: publishDecision, browserCanApprove: false },
    })
    await store.appendEvent(task.id, {
      type: 'activity_delta', lane: 'activity', label: 'Safe fallback selected',
      content: 'Public publication was withheld. Source and local preview remain available.',
      payload: { decision: 'withhold_publication', approvalPending: true },
    })
    await store.setPlanStep(task.id, 'verify', 'completed')

    await store.setPlanStep(task.id, 'deliver', 'running')
    await pause(320, signal)
    await store.setPlanStep(task.id, 'deliver', 'completed')
    await store.appendEvent(task.id, {
      type: 'run_completed', lane: 'control', status: 'completed', label: 'Task completed safely',
      content: 'The artifact is ready locally. Publication is still pending in the separate wallet.',
      payload: { published: false, evidenceChainValid: store.verifyChain(task.id) },
    })
    await store.updateTask(task.id, { status: 'completed' })
  }
}
