import type { RuntimeProviderState } from './types.js'
export type { RuntimeProviderState } from './types.js'

export const runtimeReadiness = (configuration: { claudeConfigured: boolean; claudeTransport?: 'litellm' | 'unconfigured'; codexConfigured?: boolean; agentCoreConfigured?: boolean; remoteConfigured: boolean; oneComputerConfigured: boolean; oneComputerReachable?: boolean; a2aConfigured?: boolean; kimiConfigured?: boolean }): { providers: RuntimeProviderState[] } => ({
  providers: [
    { id: 'demo', label: 'Simulation · no model call', boundary: 'Local task workspace', available: true, detail: 'Deterministic simulation for UI contracts only; never a provider or VM claim.', capabilities: ['streaming', 'file_system', 'preview_url'] },
    { id: 'claude_sdk', label: 'Claude SDK · LiteLLM', boundary: 'Governed host workspace', available: configuration.claudeConfigured && configuration.claudeTransport === 'litellm', detail: configuration.claudeConfigured && configuration.claudeTransport === 'litellm' ? 'Native Claude Agent SDK using the server-controlled LiteLLM gateway.' : 'Configure the protected LiteLLM gateway to enable this runtime.', capabilities: ['streaming', 'tool_use', 'file_system', 'preview_url'] },
    { id: 'codex', label: 'Codex-compatible · LiteLLM', boundary: 'Governed host workspace', available: configuration.codexConfigured === true, detail: configuration.codexConfigured === true ? 'Coding runtime routed through the server-controlled LiteLLM gateway; workspace tools remain path-confined.' : 'Configure the protected LiteLLM gateway to enable this runtime.', capabilities: ['streaming', 'tool_use', 'file_system'] },
    { id: 'agentcore', label: 'AWS AgentCore · LiteLLM route', boundary: 'Remote governed runtime', available: configuration.agentCoreConfigured === true, detail: configuration.agentCoreConfigured === true ? 'Remote AgentCore endpoint is configured with an explicit LiteLLM-routed model contract; isolation is not inferred.' : 'Configure an AgentCore runtime endpoint with explicit LiteLLM routing.', capabilities: ['streaming', 'tool_use'] },
    { id: 'onecomputer', label: 'ONEComputer', boundary: 'Conversation development sandbox', available: configuration.oneComputerConfigured && configuration.oneComputerReachable !== false, detail: !configuration.oneComputerConfigured ? 'Configure the ONEComputer service endpoint and server-only credentials.' : configuration.oneComputerReachable === false ? 'Configured provider is currently unreachable from the ONEVibe API.' : 'Authenticated retained sandbox runtime with one fenced lease per conversation.', capabilities: ['streaming', 'tool_use', 'file_system', 'sandboxed', 'preview_url', 'computer_use'] },
    { id: 'remote', label: 'Remote runtime', boundary: 'Remote governed runtime', available: configuration.remoteConfigured, detail: configuration.remoteConfigured ? 'Configured remote task runtime.' : 'Configure ONEVIBE_RUNTIME_URL to enable this provider.', capabilities: ['streaming', 'tool_use', 'file_system'] },
    { id: 'a2a', label: 'A2A agent · JSON-RPC', boundary: 'Remote governed runtime', available: configuration.a2aConfigured === true, detail: configuration.a2aConfigured === true ? 'A2A-compatible agent endpoint discovered through its Agent Card; JSON-RPC message/stream streaming.' : 'Configure ONEVIBE_A2A_BASE_URL to enable this provider.', capabilities: ['streaming', 'tool_use'] },
    { id: 'kimi', label: 'Kimi Code CLI', boundary: 'Local agent CLI server', available: configuration.kimiConfigured === true, detail: configuration.kimiConfigured === true ? 'Local Kimi Code CLI server; prompts run over its REST API with polled messages projected into the durable timeline.' : 'Configure KIMI_SERVER_URL to enable this provider.', capabilities: ['streaming', 'tool_use', 'file_system'] },
  ],
})
