export type SandboxSlide = { title: string; summary: string }

export const sandboxSlideSeed = (title: string, prompt: string): SandboxSlide[] => {
  const focus = prompt.replace(/\s+/g, ' ').trim().slice(0, 260)
  return [
    { title, summary: `Executive update prepared for the requested outcome: ${focus}` },
    { title: 'The decision in view', summary: `Align on the smallest governed next step that advances this outcome: ${focus}` },
    { title: 'Why this matters now', summary: 'Capable agents increase the pace and reach of work. Enterprises need a useful workspace boundary that keeps policy and accountability visible.' },
    { title: 'Recommended approach', summary: 'Provide isolated, conversation-scoped workspaces with server-custodied credentials, durable history, and portable artifacts for review.' },
    { title: 'How the work flows', summary: 'An administrator sets enterprise policy, a manager adds team guardrails, and an employee starts a bounded agent task with evidence retained.' },
    { title: 'Risk and controls', summary: 'Keep consequential approval outside the browser, minimize runtime permissions, constrain egress, and preserve an append-only evidence trail.' },
    { title: 'Measures of progress', summary: 'Track successful task completion, policy interventions, artifact integrity, runtime cleanup, and evidence-chain verification.' },
    { title: 'Recommended next step', summary: 'Complete the backend E2E proof, review the resulting evidence with security stakeholders, then harden isolation and approval integration.' },
  ]
}

export const SANDBOX_SLIDE_RENDERER = String.raw`const fs=require('node:fs');
const PptxGenJS=require('pptxgenjs'); const {PDFDocument,StandardFonts,rgb}=require('pdf-lib');
const esc=s=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
const wrap=(text,max,font,size)=>{const out=[];let line='';for(const word of text.replace(/\s+/g,' ').trim().split(' ')){const next=line?line+' '+word:word;if(line&&font.widthOfTextAtSize(next,size)>max){out.push(line);line=word}else line=next}if(line)out.push(line);return out};
(async()=>{const slides=JSON.parse(fs.readFileSync('outline.json','utf8'));if(!Array.isArray(slides)||slides.length!==8)throw new Error('outline.json must contain exactly eight slides');
const clean=slides.map((s,i)=>{if(typeof s.title!=='string'||typeof s.summary!=='string'||s.title.trim().length<3||s.summary.trim().length<20)throw new Error('invalid slide '+(i+1));return {number:i+1,title:s.title.trim().slice(0,100),summary:s.summary.trim().slice(0,300)}});fs.writeFileSync('outline.json',JSON.stringify(clean,null,2)+'\n');
const deck=new PptxGenJS();deck.layout='LAYOUT_WIDE';deck.author='ONEVibe';deck.subject='Governed sandbox deck';for(const [i,s] of clean.entries()){const slide=deck.addSlide();slide.background={color:'090B0A'};slide.addShape(deck.ShapeType.rect,{x:.45,y:.45,w:.08,h:.35,fill:{color:'38DC7D'},line:{color:'38DC7D'}});slide.addText('ONEVIBE / GOVERNED AGENT WORKSPACE',{x:.7,y:.43,w:6,h:.3,fontFace:'Arial',fontSize:9,bold:true,color:'38DC7D',charSpacing:1.5});slide.addText(s.title,{x:.7,y:1.55,w:11.8,h:1.5,fontFace:'Arial',fontSize:i===0?44:38,bold:true,color:'F3F6F4',margin:0});slide.addText(s.summary,{x:.72,y:3.25,w:9.7,h:1.1,fontFace:'Arial',fontSize:18,color:'9AA59E',margin:0});slide.addText(String(i+1).padStart(2,'0'),{x:11.9,y:6.75,w:.7,h:.3,fontFace:'Arial',fontSize:9,color:'647068',align:'right'})}await deck.writeFile({fileName:'deck.pptx',compression:true});
const pdf=await PDFDocument.create(),regular=await pdf.embedFont(StandardFonts.Helvetica),bold=await pdf.embedFont(StandardFonts.HelveticaBold);for(const [i,s] of clean.entries()){const p=pdf.addPage([960,540]);p.drawRectangle({x:0,y:0,width:960,height:540,color:rgb(.035,.043,.04)});p.drawText('ONEVIBE / GOVERNED AGENT WORKSPACE',{x:52,y:489,size:10,font:bold,color:rgb(.22,.86,.49)});wrap(s.title,820,bold,38).slice(0,3).forEach((x,j)=>p.drawText(x,{x:52,y:405-j*44,size:38,font:bold,color:rgb(.95,.965,.955)}));wrap(s.summary,690,regular,18).slice(0,6).forEach((x,j)=>p.drawText(x,{x:54,y:275-j*28,size:18,font:regular,color:rgb(.6,.65,.62)}));p.drawText(String(i+1).padStart(2,'0'),{x:870,y:28,size:9,font:bold,color:rgb(.39,.44,.41)})}fs.writeFileSync('deck.pdf',await pdf.save());
fs.writeFileSync('speaker-notes.md',clean.map(s=>'## '+s.number+'. '+s.title+'\n\n'+s.summary+'\n').join('\n'));fs.writeFileSync('README.md','# ONEVibe executive deck\n\nGenerated inside a ONEComputer sandbox using the managed deterministic renderer. Review before external distribution.\n');fs.writeFileSync('index.html','<!doctype html><meta charset="utf-8"><title>ONEVibe deck</title><style>body{font-family:system-ui;background:#090b0a;color:#f3f6f4;margin:0;padding:6vw}.slide{border:1px solid #29332d;border-radius:14px;padding:40px;margin:18px 0;background:#101411}small{color:#38dc7d}p{color:#9aa59e;line-height:1.6}</style>'+clean.map(s=>'<article class="slide"><small>SLIDE '+s.number+'</small><h1>'+esc(s.title)+'</h1><p>'+esc(s.summary)+'</p></article>').join(''));const pptx=fs.readFileSync('deck.pptx'),pdfBytes=fs.readFileSync('deck.pdf');if(pptx[0]!==0x50||pptx[1]!==0x4b)throw new Error('invalid PPTX signature');if(pdfBytes.subarray(0,5).toString()!=='%PDF-')throw new Error('invalid PDF signature');})().catch(e=>{console.error(e);process.exit(1)});`
